[REV] some words and syntax revision.

diff --git a/cpu/cpu-z b/cpu/cpu-z
--- a/cpu/cpu-z
+++ b/cpu/cpu-z
@@ -18,40 +18,38 @@ set -e
 #echo -e "\033[1;37;41m Processor(s) \033[0m"
 echo -e "\033[1mProcessor(s)\033[0m"
 while IFS='' read -r line || [[ -n "$line" ]]; do
-	if   echo $line | grep -i -q "model name";  then
+	if   echo $line | grep -iq "model name";  then
 		CPUNAME=$(echo $line | cut -d ':' -f 2 | sed -e 's/^[[:space:]]*//' | tr -s ' ')
-	elif echo $line | grep -i -q "physical id"; then
+	elif echo $line | grep -iq "physical id"; then
 		CPUNUM=$( echo $line | cut -d ' ' -f 4)
-	elif echo $line | grep -i -q "cpu cores";   then
+	elif echo $line | grep -iq "cpu cores";   then
 		CORENUM=$(echo $line | cut -d ' ' -f 4)
 	fi
 done < <(grep -i -e "model name" -e "physical id" -e "cpu cores" /proc/cpuinfo | tail -n 3)
-echo -e -n '\t'
-echo "$((CPUNUM+1))-Socket(s) $CPUNAME, each $CORENUM Cores"
+echo -e "\t$((CPUNUM+1))-Socket(s) $CPUNAME, each $CORENUM Cores"
 
 # Memory
 echo -e "\033[1mSystem Memory\033[0m"
 MEMSIZE=$(grep -i "memtotal" /proc/meminfo | tr -dc '0-9')
-echo -e -n '\t'
-echo "$((MEMSIZE/1024)) MiB"
+echo -e "\t$((MEMSIZE/1024)) MiB"
 
 # NorthBridge I/Os
 if command -v lspci >/dev/null 2>&1; then
 	echo -e "\033[1mGPU Accelerator(s)\033[0m"
 	while IFS='' read -r line || [[ -n "$line" ]]; do
-		echo -e -n '\t'
+		echo -ne '\t'
 		echo $line | cut -d ':' -f 3 | sed -e 's/^[[:space:]]*//'
 	done < <(lspci | grep -i "nvidia" || echo "NONE NVIDIA GPU(s) detected!")
 
 	echo -e "\033[1mInfiniBand HCA(s)\033[0m"
 	while IFS='' read -r line || [[ -n "$line" ]]; do
-		echo -e -n '\t'
+		echo -ne '\t'
 		echo $line | cut -d ':' -f 3 | sed -e 's/^[[:space:]]*//'
 	done < <(lspci | grep -i "mellanox" || echo "NONE Mellanox HCA(s) detected!")
 
 	echo -e "\033[1mPCIe SSD Controllor(s)\033[0m"
 	while IFS='' read -r line || [[ -n "$line" ]]; do
-		echo -e -n '\t'
+		echo -ne '\t'
 		echo $line | cut -c 9-
 	done < <(lspci | grep -i "1c5f" || echo "@ @ @ @ NONE Memblaze SSD(s) detected!")
 else
@@ -62,10 +60,10 @@ fi
 if command -v lsblk >/dev/null 2>&1; then
 	echo -e "\033[1mSCSI/SATA HDD(s)/SSD(s)\033[0m"
 	while IFS='' read -r line || [[ -n "$line" ]]; do
-		echo -e -n '\t'
+		echo -ne '\t'
 		echo $line | cut -d ' ' -f 3-
 		#echo $line | cut -d ' ' -f 3- | sed -r 's/ ([^ ]*)$/, \1/'
-	done < <(lsblk -o TYPE,NAME,MODEL,SIZE | grep -i "disk" | grep -i "sd" || echo -e "@ @ NONE HDD(s) detected!")
+	done < <(lsblk -o TYPE,NAME,MODEL,SIZE | grep -i "disk" | grep -i "sd" || echo "@ @ NONE HDD(s) detected!")
 else
 	echo >&2 "ERROR: lsblk required! Please yum install util-linux-ng!"
 fi
@@ -73,39 +71,38 @@ fi
 # Operating System
 echo -e "\033[1mOS Distro\033[0m"
 if [ -f /etc/centos-release ]; then
-	echo -e -n '\t'
+	echo -ne '\t'
 	echo $(cat /etc/centos-release)
 elif [ -f /etc/redhat-release ]; then
-	echo -e -n '\t'
+	echo -ne '\t'
 	echo $(cat /etc/redhat-release)
 elif [ -f /etc/lsb-release ]; then
-	echo -e -n '\t'
+	echo -ne '\t'
 	echo $(cat /etc/lsb-release | grep -i description | cut -d '"' -f 2)
 else
-	echo -e -n '\t'
-	echo "Unrecognized Linux Distro ..."
+	echo -e "\tUnrecognized Linux Distro ..."
 fi
 
 # Kernel
 echo -e "\033[1mOS Kernel\033[0m"
-echo -e -n '\t'
+echo -ne '\t'
 echo $(uname -sr)
 if command -v rpm >/dev/null 2>&1; then
 	rpm -q kernel-devel-$(uname -r)      >/dev/null 2>&1 || \
 	rpm -q kernel-lt-devel-$(uname -r)   >/dev/null 2>&1 || \
-	{ echo -e -n '\t'; echo >&2 "WARNING: failed to find package kernel-devel for current kernel ...";   }
+	{ echo -ne '\t'; echo >&2 "WARNING: failed to find package kernel-devel for current kernel ...";   }
 	rpm -q kernel-headers-$(uname -r)    >/dev/null 2>&1 || \
 	rpm -q kernel-lt-headers-$(uname -r) >/dev/null 2>&1 || \
-	{ echo -e -n '\t'; echo >&2 "WARNING: failed to find package kernel-headers for current kernel ..."; }
+	{ echo -ne '\t'; echo >&2 "WARNING: failed to find package kernel-headers for current kernel ..."; }
 elif command -v dpkg >/dev/null 2>&1; then
 	dpkg -l linux-headers-$(uname -r)    >/dev/null 2>&1 || \
-	{ echo -e -n '\t'; echo >&2 "WARNING: failed to find package linux-headers for current kernel ...";  }
+	{ echo -ne '\t'; echo >&2 "WARNING: failed to find package linux-headers for current kernel ...";  }
 fi
 
 # GCC
 if command -v gcc >/dev/null 2>&1; then
 	echo -e "\033[1mGCC Compiler\033[0m"
-	echo -e -n '\t'
+	echo -ne '\t'
 	echo $(gcc --version | head -n 1 | cut -c 4-)
 else
 	echo "GCC not installed! Please yum install gcc gcc-c++!"
@@ -114,6 +111,6 @@ fi
 # CUDA driver
 if [ -e /proc/driver/nvidia/version ]; then
 	echo -e "\033[1mCUDA Driver\033[0m"
-	echo -e -n '\t'
+	echo -ne '\t'
 	echo $(head -n 1 /proc/driver/nvidia/version | tr -s ' ' | cut -d ' ' -f 3-8)
 fi
diff --git a/cpu/cpufreq b/cpu/cpufreq
--- a/cpu/cpufreq
+++ b/cpu/cpufreq
@@ -5,26 +5,26 @@
 
 set -e
 
-if [[ -z $1 ]]; then
-	echo "Argument(s) required!" >&2
+if [ -z $1 ]; then
+	echo "Argument(s) Required!" >&2
 	echo "Usage: $(basename $0) [lock|unlock]"
 	exit 1
 fi
 
-if [[ ! -z $1 && $1 != "lock" && $1 != "unlock" ]]; then
+if [[ $1 != "lock" && $1 != "unlock" ]]; then
 	echo "Invalid argument(s): $1" >&2
 	echo "Usage: $(basename $0) [lock|unlock]"
 	exit 1
 fi
 
-if [[ $1 == "lock" ]]; then
+if [ $1 == "lock" ]; then
 #	echo "1"  | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
 #	echo "99" | sudo tee /sys/devices/system/cpu/intel_pstate/min_perf_pct
 	echo "1"  > "/sys/devices/system/cpu/intel_pstate/no_turbo"     2> /dev/null
 	echo "99" > "/sys/devices/system/cpu/intel_pstate/min_perf_pct" 2> /dev/null
 fi
 
-if [[ $1 == "unlock" ]]; then
+if [ $1 == "unlock" ]; then
 	echo "0"  > "/sys/devices/system/cpu/intel_pstate/no_turbo"     2> /dev/null
 #	echo "25" > "/sys/devices/system/cpu/intel_pstate/min_perf_pct" 2> /dev/null
 	echo "37" > "/sys/devices/system/cpu/intel_pstate/min_perf_pct" 2> /dev/null
diff --git a/cpu/cpufreq-governor b/cpu/cpufreq-governor
--- a/cpu/cpufreq-governor
+++ b/cpu/cpufreq-governor
@@ -3,26 +3,26 @@
 
 set -e
 
-if [[ -z $1 ]]; then
-	echo "Argument(s) required!" >&2
+if [ -z $1 ]; then
+	echo "Argument(s) Required!" >&2
 	echo "Usage: $(basename $0) [powersave|performance]"
 	exit 1
 fi
 
-if [[ ! -z $1 && $1 != "powersave" && $1 != "performance" ]]; then
-	echo "Invalid argument(s): $1" >&2
+if [[ $1 != "powersave" && $1 != "performance" ]]; then
+	echo "Invalid Argument(s): $1" >&2
 	echo "Usage: $(basename $0) [powersave|performance]"
 	exit 1
 fi
 
-if [[ $1 == "powersave" ]]; then
+if [ $1 == "powersave" ]; then
 	for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
 		[ -f $CPUFREQ ] || continue
 		echo -n "powersave" > $CPUFREQ 2> /dev/null
 	done
 fi
 
-if [[ $1 == "performance" ]]; then
+if [ $1 == "performance" ]; then
 	for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
 		[ -f $CPUFREQ ] || continue
 		echo -n "performance" > $CPUFREQ 2> /dev/null
diff --git a/misc/selinux b/misc/selinux
--- a/misc/selinux
+++ b/misc/selinux
@@ -15,7 +15,7 @@ if [[ $1 != "enforcing" && $1 != "permissive" && $1 != "disabled" ]]; then
 	exit 1
 fi
 
-[ -f /etc/selinux/config ] || { echo "ERROR: /etc/selinux/config not found!"; exit 1; }
+[ -f /etc/selinux/config ] || { echo "ERROR: /etc/selinux/config not found!" >&2; exit 1; }
 
 if   [ $1 == "enforcing"  ]; then
 	sed -i -- 's/^SELINUX=.\+/SELINUX=enforcing/g'  /etc/selinux/config
